### ISSUE TITLE
numerical error with 'nan'

### ISSUE THREAD

**Issue by Kid-key** [ruosongwang/CNTK#1]
Hi, I sampled 500(train)+100(test) images to run your code, however, I found an error when calculating the prediction values, that kernel matrix contains 'nan' value and scipy.linalg fails to solve. Is this normal and what should I deal with it? 
Thank you 

Error details:
    u = H[N_train:, :N_train].dot(scipy.linalg.solve(H[:N_train, :N_train], Y_train))
ValueError: array must not contain infs or NaNs

**Comment by ruosongwang** [comment]
Thanks for your interest in our work.

Having nan is abnormal. Please make sure that the data is in an cparray with dtype=float32, since we explicitly assume 32bit floating-point numbers. Also, it is known that if some data is zero (all entries are all zero), then a kernel value of nan might be returned. However that should not appear in CIFAR10. 


I can provide more suggestions if you kindly share the code with me.
